SET search_path TO onboarding, public;

ALTER TABLE ddq_pack_item
    ADD COLUMN IF NOT EXISTS parent_branch_item_id INT NULL,
    ADD COLUMN IF NOT EXISTS parent_branch_option_id TEXT NULL;

ALTER TABLE ddq_pack_item
    DROP CONSTRAINT IF EXISTS ddq_pack_item_kind_check,
    ADD CONSTRAINT ddq_pack_item_kind_check
        CHECK (kind IN ('ddq-task', 'checkpoint', 'branch'));

ALTER TABLE ddq_pack_item
    DROP CONSTRAINT IF EXISTS ddq_pack_item_task_consistency_check,
    ADD CONSTRAINT ddq_pack_item_task_consistency_check CHECK (
        (kind = 'ddq-task' AND task_type IS NOT NULL)
        OR
        (kind IN ('checkpoint', 'branch') AND task_type IS NULL)
    );

ALTER TABLE ddq_pack_item
    ADD CONSTRAINT ddq_pack_item_parent_branch_fk
        FOREIGN KEY (parent_branch_item_id)
        REFERENCES ddq_pack_item(id)
        ON DELETE CASCADE,
    ADD CONSTRAINT ddq_pack_item_parent_option_consistency_check CHECK (
        (parent_branch_item_id IS NULL AND parent_branch_option_id IS NULL)
        OR
        (parent_branch_item_id IS NOT NULL AND parent_branch_option_id IS NOT NULL)
    );

CREATE INDEX IF NOT EXISTS ddq_pack_item_parent_position_idx
    ON ddq_pack_item(
        pack_id,
        COALESCE(parent_branch_item_id, 0),
        COALESCE(parent_branch_option_id, ''),
        position
    );

CREATE TABLE IF NOT EXISTS provider_ddq_checklist_branch_selection (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checklist_id INT NOT NULL,
    branch_pack_item_id INT NOT NULL,
    selected_option_id TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT provider_ddq_checklist_branch_selection_checklist_fk
        FOREIGN KEY (checklist_id)
        REFERENCES provider_ddq_checklist(id)
        ON DELETE CASCADE,
    CONSTRAINT provider_ddq_checklist_branch_selection_branch_fk
        FOREIGN KEY (branch_pack_item_id)
        REFERENCES ddq_pack_item(id)
        ON DELETE CASCADE,
    CONSTRAINT provider_ddq_checklist_branch_selection_unique
        UNIQUE (checklist_id, branch_pack_item_id)
);

CREATE INDEX IF NOT EXISTS provider_ddq_checklist_branch_selection_checklist_idx
    ON provider_ddq_checklist_branch_selection(checklist_id);
