SET search_path TO onboarding, public;

CREATE TABLE IF NOT EXISTS form_templates (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    association_corporation_id INT NOT NULL,
    short_name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    schema_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT form_templates_association_corporation_fk
        FOREIGN KEY (association_corporation_id)
        REFERENCES corporation(id)
        ON DELETE CASCADE,
    CONSTRAINT form_templates_schema_version_check
        CHECK ((schema_json->>'version') IS NOT NULL AND (schema_json->>'version') = '1'),
    CONSTRAINT form_templates_schema_items_check
        CHECK (schema_json ? 'items' AND jsonb_typeof(schema_json->'items') = 'array')
);

CREATE INDEX IF NOT EXISTS form_templates_association_corporation_idx
    ON form_templates(association_corporation_id);

CREATE INDEX IF NOT EXISTS form_templates_created_at_idx
    ON form_templates(created_at DESC, id DESC);
