SET search_path TO onboarding, public;

CREATE TABLE IF NOT EXISTS corporation (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    CONSTRAINT corporation_type_check CHECK (type IN ('ASSOCIATION', 'PROVIDER', 'AGENT', 'STAKEHOLDER')),
    CONSTRAINT corporation_status_check CHECK (status IN ('pending', 'approved', 'rejected'))
);

CREATE TABLE IF NOT EXISTS app_user (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corporation_id INT NOT NULL,
    cognito_sub VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(32) NOT NULL,
    permissions TEXT[] NOT NULL DEFAULT '{}',
    CONSTRAINT app_user_corporation_id_fk
        FOREIGN KEY (corporation_id)
        REFERENCES corporation(id)
        ON DELETE CASCADE,
    CONSTRAINT app_user_status_check CHECK (status IN ('invited', 'active', 'disabled'))
);

CREATE TABLE IF NOT EXISTS corporation_application (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(32) NOT NULL,
    applicant_email VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    CONSTRAINT corporation_application_type_check CHECK (type IN ('PROVIDER', 'AGENT', 'STAKEHOLDER')),
    CONSTRAINT corporation_application_status_check CHECK (status IN ('pending', 'approved', 'rejected'))
);

CREATE TABLE IF NOT EXISTS corporation_access_request (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_corporation_id INT NOT NULL,
    provider_corporation_id INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    CONSTRAINT corporation_access_request_requester_fk
        FOREIGN KEY (requester_corporation_id)
        REFERENCES corporation(id)
        ON DELETE CASCADE,
    CONSTRAINT corporation_access_request_provider_fk
        FOREIGN KEY (provider_corporation_id)
        REFERENCES corporation(id)
        ON DELETE CASCADE,
    CONSTRAINT corporation_access_request_status_check CHECK (status IN ('pending', 'approved', 'rejected'))
);
