SET search_path TO onboarding, public;

CREATE TABLE IF NOT EXISTS provider_ddq_pack (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_corporation_id INT NOT NULL,
    ddq_pack_id INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT provider_ddq_pack_provider_fk
        FOREIGN KEY (provider_corporation_id)
        REFERENCES corporation(id)
        ON DELETE CASCADE,
    CONSTRAINT provider_ddq_pack_pack_fk
        FOREIGN KEY (ddq_pack_id)
        REFERENCES ddq_pack(id)
        ON DELETE CASCADE,
    CONSTRAINT provider_ddq_pack_unique
        UNIQUE (provider_corporation_id, ddq_pack_id)
);
