SET search_path TO onboarding, public;

CREATE TABLE IF NOT EXISTS ddq_pack (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NOT NULL,
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ddq_pack_valid_dates_check CHECK (valid_to >= valid_from)
);

CREATE TABLE IF NOT EXISTS ddq_pack_item (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack_id INT NOT NULL,
    position INT NOT NULL,
    kind VARCHAR(32) NOT NULL,
    task_type VARCHAR(64),
    title VARCHAR(255) NOT NULL,
    config JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ddq_pack_item_pack_fk
        FOREIGN KEY (pack_id)
        REFERENCES ddq_pack(id)
        ON DELETE CASCADE,
    CONSTRAINT ddq_pack_item_kind_check CHECK (kind IN ('ddq-task', 'checkpoint')),
    CONSTRAINT ddq_pack_item_task_consistency_check CHECK (
        (kind = 'ddq-task' AND task_type IS NOT NULL)
        OR
        (kind = 'checkpoint' AND task_type IS NULL)
    )
);
