SET search_path TO onboarding, public;

CREATE TABLE IF NOT EXISTS provider_ddq_checklist_task_form_response (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checklist_task_id INT NOT NULL UNIQUE,
    form_document JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ NULL,
    CONSTRAINT provider_ddq_checklist_task_form_response_task_fk
        FOREIGN KEY (checklist_task_id)
        REFERENCES provider_ddq_checklist_task(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS provider_ddq_checklist_task_form_response_task_idx
    ON provider_ddq_checklist_task_form_response(checklist_task_id);
