SET search_path TO onboarding, public;

CREATE TABLE IF NOT EXISTS provider_ddq_checklist (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_ddq_pack_id INT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT provider_ddq_checklist_pack_fk
        FOREIGN KEY (provider_ddq_pack_id)
        REFERENCES provider_ddq_pack(id)
        ON DELETE CASCADE,
    CONSTRAINT provider_ddq_checklist_pack_unique
        UNIQUE (provider_ddq_pack_id),
    CONSTRAINT provider_ddq_checklist_status_check
        CHECK (status IN ('active', 'completed', 'withdrawn'))
);

CREATE TABLE IF NOT EXISTS provider_ddq_checklist_task (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checklist_id INT NOT NULL,
    ddq_pack_item_id INT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT provider_ddq_checklist_task_checklist_fk
        FOREIGN KEY (checklist_id)
        REFERENCES provider_ddq_checklist(id)
        ON DELETE CASCADE,
    CONSTRAINT provider_ddq_checklist_task_pack_item_fk
        FOREIGN KEY (ddq_pack_item_id)
        REFERENCES ddq_pack_item(id)
        ON DELETE RESTRICT,
    CONSTRAINT provider_ddq_checklist_task_unique
        UNIQUE (checklist_id, ddq_pack_item_id),
    CONSTRAINT provider_ddq_checklist_task_status_check
        CHECK (status IN ('active', 'completed', 'withdrawn'))
);
