SET search_path TO onboarding, public;

CREATE TABLE IF NOT EXISTS provider_ddq_checklist_task_evidence (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checklist_task_id INT NOT NULL,
    uploaded_by_app_user_id INT NOT NULL,
    object_key VARCHAR(64) NOT NULL UNIQUE,
    original_filename TEXT NOT NULL,
    content_type TEXT NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending_upload',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    uploaded_at TIMESTAMPTZ NULL,
    replaced_at TIMESTAMPTZ NULL,
    CONSTRAINT provider_ddq_checklist_task_evidence_task_fk
        FOREIGN KEY (checklist_task_id)
        REFERENCES provider_ddq_checklist_task(id)
        ON DELETE CASCADE,
    CONSTRAINT provider_ddq_checklist_task_evidence_user_fk
        FOREIGN KEY (uploaded_by_app_user_id)
        REFERENCES app_user(id)
        ON DELETE RESTRICT,
    CONSTRAINT provider_ddq_checklist_task_evidence_status_check
        CHECK (status IN ('pending_upload', 'uploaded', 'replaced', 'failed')),
    CONSTRAINT provider_ddq_checklist_task_evidence_size_check
        CHECK (file_size_bytes > 0)
);

CREATE INDEX IF NOT EXISTS idx_provider_ddq_checklist_task_evidence_task
    ON provider_ddq_checklist_task_evidence(checklist_task_id);

CREATE TABLE IF NOT EXISTS provider_ddq_checklist_task_evidence_tag (
    evidence_id INT NOT NULL,
    tag TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'manual',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT provider_ddq_checklist_task_evidence_tag_evidence_fk
        FOREIGN KEY (evidence_id)
        REFERENCES provider_ddq_checklist_task_evidence(id)
        ON DELETE CASCADE,
    CONSTRAINT provider_ddq_checklist_task_evidence_tag_pk
        PRIMARY KEY (evidence_id, tag, source),
    CONSTRAINT provider_ddq_checklist_task_evidence_tag_not_blank
        CHECK (LENGTH(TRIM(tag)) > 0),
    CONSTRAINT provider_ddq_checklist_task_evidence_tag_source_check
        CHECK (source IN ('manual', 'recognition'))
);

CREATE INDEX IF NOT EXISTS idx_provider_ddq_checklist_task_evidence_tag
    ON provider_ddq_checklist_task_evidence_tag(LOWER(tag));
