SET search_path TO onboarding, public;

CREATE TABLE IF NOT EXISTS subject (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_corporation_id INT NOT NULL,
    subject_type_key TEXT NOT NULL,
    display_name TEXT NOT NULL,
    values_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by_app_user_id INT NULL,
    updated_by_app_user_id INT NULL,
    archived_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT subject_provider_corporation_fk
        FOREIGN KEY (provider_corporation_id)
        REFERENCES corporation(id)
        ON DELETE CASCADE,
    CONSTRAINT subject_created_by_user_fk
        FOREIGN KEY (created_by_app_user_id)
        REFERENCES app_user(id)
        ON DELETE SET NULL,
    CONSTRAINT subject_updated_by_user_fk
        FOREIGN KEY (updated_by_app_user_id)
        REFERENCES app_user(id)
        ON DELETE SET NULL,
    CONSTRAINT subject_values_object_check
        CHECK (jsonb_typeof(values_json) = 'object'),
    CONSTRAINT subject_display_name_not_blank
        CHECK (LENGTH(TRIM(display_name)) > 0),
    CONSTRAINT subject_type_key_not_blank
        CHECK (LENGTH(TRIM(subject_type_key)) > 0)
);

CREATE INDEX IF NOT EXISTS subject_provider_type_updated_idx
    ON subject(provider_corporation_id, subject_type_key, updated_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS subject_provider_display_name_idx
    ON subject(provider_corporation_id, LOWER(display_name));

CREATE INDEX IF NOT EXISTS subject_provider_active_idx
    ON subject(provider_corporation_id, archived_at)
    WHERE archived_at IS NULL;
